spring:
  application:
    name: vehicle-ingestion-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8081

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    displayOperationId: true
  show-actuator: false
  
openapi:
  info:
    title: Vehicle Ingestion Service API
    description: API para ingestão de dados de telemetria de veículos em tempo real
    version: 1.0.0
    contact:
      name: Telemetry Team
    license:
      name: Apache 2.0
